/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolsRouteImport } from './routes/vols'
import { Route as TransportsRouteImport } from './routes/transports'
import { Route as RegieRouteImport } from './routes/regie'
import { Route as RecrutementRouteImport } from './routes/recrutement'
import { Route as PresseRouteImport } from './routes/presse'
import { Route as PreparerRouteImport } from './routes/preparer'
import { Route as ParkingRouteImport } from './routes/parking'
import { Route as KinshasaRouteImport } from './routes/kinshasa'
import { Route as DestinationsRouteImport } from './routes/destinations'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AeroportRouteImport } from './routes/aeroport'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VolsDetailRouteImport } from './routes/vols.detail'
import { Route as VolsDepartsRouteImport } from './routes/vols.departs'
import { Route as VolsCompagniesRouteImport } from './routes/vols.compagnies'
import { Route as VolsArriveesRouteImport } from './routes/vols.arrivees'
import { Route as TransportsTaxiRouteImport } from './routes/transports.taxi'
import { Route as TransportsBusRouteImport } from './routes/transports.bus'
import { Route as PreparerSecuriteRouteImport } from './routes/preparer.securite'
import { Route as PreparerFamillesRouteImport } from './routes/preparer.familles'
import { Route as PreparerEnregistrementRouteImport } from './routes/preparer.enregistrement'
import { Route as KinshasaVisiterRouteImport } from './routes/kinshasa.visiter'
import { Route as KinshasaHotelsRouteImport } from './routes/kinshasa.hotels'
import { Route as KinshasaAffairesRouteImport } from './routes/kinshasa.affaires'
import { Route as AeroportServicesRouteImport } from './routes/aeroport.services'
import { Route as AeroportBoutiquesRouteImport } from './routes/aeroport.boutiques'

const VolsRoute = VolsRouteImport.update({
  id: '/vols',
  path: '/vols',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportsRoute = TransportsRouteImport.update({
  id: '/transports',
  path: '/transports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegieRoute = RegieRouteImport.update({
  id: '/regie',
  path: '/regie',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementRoute = RecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => rootRouteImport,
} as any)
const PresseRoute = PresseRouteImport.update({
  id: '/presse',
  path: '/presse',
  getParentRoute: () => rootRouteImport,
} as any)
const PreparerRoute = PreparerRouteImport.update({
  id: '/preparer',
  path: '/preparer',
  getParentRoute: () => rootRouteImport,
} as any)
const ParkingRoute = ParkingRouteImport.update({
  id: '/parking',
  path: '/parking',
  getParentRoute: () => rootRouteImport,
} as any)
const KinshasaRoute = KinshasaRouteImport.update({
  id: '/kinshasa',
  path: '/kinshasa',
  getParentRoute: () => rootRouteImport,
} as any)
const DestinationsRoute = DestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AeroportRoute = AeroportRouteImport.update({
  id: '/aeroport',
  path: '/aeroport',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VolsDetailRoute = VolsDetailRouteImport.update({
  id: '/detail',
  path: '/detail',
  getParentRoute: () => VolsRoute,
} as any)
const VolsDepartsRoute = VolsDepartsRouteImport.update({
  id: '/departs',
  path: '/departs',
  getParentRoute: () => VolsRoute,
} as any)
const VolsCompagniesRoute = VolsCompagniesRouteImport.update({
  id: '/compagnies',
  path: '/compagnies',
  getParentRoute: () => VolsRoute,
} as any)
const VolsArriveesRoute = VolsArriveesRouteImport.update({
  id: '/arrivees',
  path: '/arrivees',
  getParentRoute: () => VolsRoute,
} as any)
const TransportsTaxiRoute = TransportsTaxiRouteImport.update({
  id: '/taxi',
  path: '/taxi',
  getParentRoute: () => TransportsRoute,
} as any)
const TransportsBusRoute = TransportsBusRouteImport.update({
  id: '/bus',
  path: '/bus',
  getParentRoute: () => TransportsRoute,
} as any)
const PreparerSecuriteRoute = PreparerSecuriteRouteImport.update({
  id: '/securite',
  path: '/securite',
  getParentRoute: () => PreparerRoute,
} as any)
const PreparerFamillesRoute = PreparerFamillesRouteImport.update({
  id: '/familles',
  path: '/familles',
  getParentRoute: () => PreparerRoute,
} as any)
const PreparerEnregistrementRoute = PreparerEnregistrementRouteImport.update({
  id: '/enregistrement',
  path: '/enregistrement',
  getParentRoute: () => PreparerRoute,
} as any)
const KinshasaVisiterRoute = KinshasaVisiterRouteImport.update({
  id: '/visiter',
  path: '/visiter',
  getParentRoute: () => KinshasaRoute,
} as any)
const KinshasaHotelsRoute = KinshasaHotelsRouteImport.update({
  id: '/hotels',
  path: '/hotels',
  getParentRoute: () => KinshasaRoute,
} as any)
const KinshasaAffairesRoute = KinshasaAffairesRouteImport.update({
  id: '/affaires',
  path: '/affaires',
  getParentRoute: () => KinshasaRoute,
} as any)
const AeroportServicesRoute = AeroportServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AeroportRoute,
} as any)
const AeroportBoutiquesRoute = AeroportBoutiquesRouteImport.update({
  id: '/boutiques',
  path: '/boutiques',
  getParentRoute: () => AeroportRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/aeroport': typeof AeroportRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/kinshasa': typeof KinshasaRouteWithChildren
  '/parking': typeof ParkingRoute
  '/preparer': typeof PreparerRouteWithChildren
  '/presse': typeof PresseRoute
  '/recrutement': typeof RecrutementRoute
  '/regie': typeof RegieRoute
  '/transports': typeof TransportsRouteWithChildren
  '/vols': typeof VolsRouteWithChildren
  '/aeroport/boutiques': typeof AeroportBoutiquesRoute
  '/aeroport/services': typeof AeroportServicesRoute
  '/kinshasa/affaires': typeof KinshasaAffairesRoute
  '/kinshasa/hotels': typeof KinshasaHotelsRoute
  '/kinshasa/visiter': typeof KinshasaVisiterRoute
  '/preparer/enregistrement': typeof PreparerEnregistrementRoute
  '/preparer/familles': typeof PreparerFamillesRoute
  '/preparer/securite': typeof PreparerSecuriteRoute
  '/transports/bus': typeof TransportsBusRoute
  '/transports/taxi': typeof TransportsTaxiRoute
  '/vols/arrivees': typeof VolsArriveesRoute
  '/vols/compagnies': typeof VolsCompagniesRoute
  '/vols/departs': typeof VolsDepartsRoute
  '/vols/detail': typeof VolsDetailRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/aeroport': typeof AeroportRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/kinshasa': typeof KinshasaRouteWithChildren
  '/parking': typeof ParkingRoute
  '/preparer': typeof PreparerRouteWithChildren
  '/presse': typeof PresseRoute
  '/recrutement': typeof RecrutementRoute
  '/regie': typeof RegieRoute
  '/transports': typeof TransportsRouteWithChildren
  '/vols': typeof VolsRouteWithChildren
  '/aeroport/boutiques': typeof AeroportBoutiquesRoute
  '/aeroport/services': typeof AeroportServicesRoute
  '/kinshasa/affaires': typeof KinshasaAffairesRoute
  '/kinshasa/hotels': typeof KinshasaHotelsRoute
  '/kinshasa/visiter': typeof KinshasaVisiterRoute
  '/preparer/enregistrement': typeof PreparerEnregistrementRoute
  '/preparer/familles': typeof PreparerFamillesRoute
  '/preparer/securite': typeof PreparerSecuriteRoute
  '/transports/bus': typeof TransportsBusRoute
  '/transports/taxi': typeof TransportsTaxiRoute
  '/vols/arrivees': typeof VolsArriveesRoute
  '/vols/compagnies': typeof VolsCompagniesRoute
  '/vols/departs': typeof VolsDepartsRoute
  '/vols/detail': typeof VolsDetailRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/aeroport': typeof AeroportRouteWithChildren
  '/contact': typeof ContactRoute
  '/destinations': typeof DestinationsRoute
  '/kinshasa': typeof KinshasaRouteWithChildren
  '/parking': typeof ParkingRoute
  '/preparer': typeof PreparerRouteWithChildren
  '/presse': typeof PresseRoute
  '/recrutement': typeof RecrutementRoute
  '/regie': typeof RegieRoute
  '/transports': typeof TransportsRouteWithChildren
  '/vols': typeof VolsRouteWithChildren
  '/aeroport/boutiques': typeof AeroportBoutiquesRoute
  '/aeroport/services': typeof AeroportServicesRoute
  '/kinshasa/affaires': typeof KinshasaAffairesRoute
  '/kinshasa/hotels': typeof KinshasaHotelsRoute
  '/kinshasa/visiter': typeof KinshasaVisiterRoute
  '/preparer/enregistrement': typeof PreparerEnregistrementRoute
  '/preparer/familles': typeof PreparerFamillesRoute
  '/preparer/securite': typeof PreparerSecuriteRoute
  '/transports/bus': typeof TransportsBusRoute
  '/transports/taxi': typeof TransportsTaxiRoute
  '/vols/arrivees': typeof VolsArriveesRoute
  '/vols/compagnies': typeof VolsCompagniesRoute
  '/vols/departs': typeof VolsDepartsRoute
  '/vols/detail': typeof VolsDetailRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/aeroport'
    | '/contact'
    | '/destinations'
    | '/kinshasa'
    | '/parking'
    | '/preparer'
    | '/presse'
    | '/recrutement'
    | '/regie'
    | '/transports'
    | '/vols'
    | '/aeroport/boutiques'
    | '/aeroport/services'
    | '/kinshasa/affaires'
    | '/kinshasa/hotels'
    | '/kinshasa/visiter'
    | '/preparer/enregistrement'
    | '/preparer/familles'
    | '/preparer/securite'
    | '/transports/bus'
    | '/transports/taxi'
    | '/vols/arrivees'
    | '/vols/compagnies'
    | '/vols/departs'
    | '/vols/detail'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/aeroport'
    | '/contact'
    | '/destinations'
    | '/kinshasa'
    | '/parking'
    | '/preparer'
    | '/presse'
    | '/recrutement'
    | '/regie'
    | '/transports'
    | '/vols'
    | '/aeroport/boutiques'
    | '/aeroport/services'
    | '/kinshasa/affaires'
    | '/kinshasa/hotels'
    | '/kinshasa/visiter'
    | '/preparer/enregistrement'
    | '/preparer/familles'
    | '/preparer/securite'
    | '/transports/bus'
    | '/transports/taxi'
    | '/vols/arrivees'
    | '/vols/compagnies'
    | '/vols/departs'
    | '/vols/detail'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/aeroport'
    | '/contact'
    | '/destinations'
    | '/kinshasa'
    | '/parking'
    | '/preparer'
    | '/presse'
    | '/recrutement'
    | '/regie'
    | '/transports'
    | '/vols'
    | '/aeroport/boutiques'
    | '/aeroport/services'
    | '/kinshasa/affaires'
    | '/kinshasa/hotels'
    | '/kinshasa/visiter'
    | '/preparer/enregistrement'
    | '/preparer/familles'
    | '/preparer/securite'
    | '/transports/bus'
    | '/transports/taxi'
    | '/vols/arrivees'
    | '/vols/compagnies'
    | '/vols/departs'
    | '/vols/detail'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  AeroportRoute: typeof AeroportRouteWithChildren
  ContactRoute: typeof ContactRoute
  DestinationsRoute: typeof DestinationsRoute
  KinshasaRoute: typeof KinshasaRouteWithChildren
  ParkingRoute: typeof ParkingRoute
  PreparerRoute: typeof PreparerRouteWithChildren
  PresseRoute: typeof PresseRoute
  RecrutementRoute: typeof RecrutementRoute
  RegieRoute: typeof RegieRoute
  TransportsRoute: typeof TransportsRouteWithChildren
  VolsRoute: typeof VolsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vols': {
      id: '/vols'
      path: '/vols'
      fullPath: '/vols'
      preLoaderRoute: typeof VolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transports': {
      id: '/transports'
      path: '/transports'
      fullPath: '/transports'
      preLoaderRoute: typeof TransportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/regie': {
      id: '/regie'
      path: '/regie'
      fullPath: '/regie'
      preLoaderRoute: typeof RegieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement': {
      id: '/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof RecrutementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/presse': {
      id: '/presse'
      path: '/presse'
      fullPath: '/presse'
      preLoaderRoute: typeof PresseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preparer': {
      id: '/preparer'
      path: '/preparer'
      fullPath: '/preparer'
      preLoaderRoute: typeof PreparerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parking': {
      id: '/parking'
      path: '/parking'
      fullPath: '/parking'
      preLoaderRoute: typeof ParkingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kinshasa': {
      id: '/kinshasa'
      path: '/kinshasa'
      fullPath: '/kinshasa'
      preLoaderRoute: typeof KinshasaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/destinations': {
      id: '/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof DestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aeroport': {
      id: '/aeroport'
      path: '/aeroport'
      fullPath: '/aeroport'
      preLoaderRoute: typeof AeroportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vols/detail': {
      id: '/vols/detail'
      path: '/detail'
      fullPath: '/vols/detail'
      preLoaderRoute: typeof VolsDetailRouteImport
      parentRoute: typeof VolsRoute
    }
    '/vols/departs': {
      id: '/vols/departs'
      path: '/departs'
      fullPath: '/vols/departs'
      preLoaderRoute: typeof VolsDepartsRouteImport
      parentRoute: typeof VolsRoute
    }
    '/vols/compagnies': {
      id: '/vols/compagnies'
      path: '/compagnies'
      fullPath: '/vols/compagnies'
      preLoaderRoute: typeof VolsCompagniesRouteImport
      parentRoute: typeof VolsRoute
    }
    '/vols/arrivees': {
      id: '/vols/arrivees'
      path: '/arrivees'
      fullPath: '/vols/arrivees'
      preLoaderRoute: typeof VolsArriveesRouteImport
      parentRoute: typeof VolsRoute
    }
    '/transports/taxi': {
      id: '/transports/taxi'
      path: '/taxi'
      fullPath: '/transports/taxi'
      preLoaderRoute: typeof TransportsTaxiRouteImport
      parentRoute: typeof TransportsRoute
    }
    '/transports/bus': {
      id: '/transports/bus'
      path: '/bus'
      fullPath: '/transports/bus'
      preLoaderRoute: typeof TransportsBusRouteImport
      parentRoute: typeof TransportsRoute
    }
    '/preparer/securite': {
      id: '/preparer/securite'
      path: '/securite'
      fullPath: '/preparer/securite'
      preLoaderRoute: typeof PreparerSecuriteRouteImport
      parentRoute: typeof PreparerRoute
    }
    '/preparer/familles': {
      id: '/preparer/familles'
      path: '/familles'
      fullPath: '/preparer/familles'
      preLoaderRoute: typeof PreparerFamillesRouteImport
      parentRoute: typeof PreparerRoute
    }
    '/preparer/enregistrement': {
      id: '/preparer/enregistrement'
      path: '/enregistrement'
      fullPath: '/preparer/enregistrement'
      preLoaderRoute: typeof PreparerEnregistrementRouteImport
      parentRoute: typeof PreparerRoute
    }
    '/kinshasa/visiter': {
      id: '/kinshasa/visiter'
      path: '/visiter'
      fullPath: '/kinshasa/visiter'
      preLoaderRoute: typeof KinshasaVisiterRouteImport
      parentRoute: typeof KinshasaRoute
    }
    '/kinshasa/hotels': {
      id: '/kinshasa/hotels'
      path: '/hotels'
      fullPath: '/kinshasa/hotels'
      preLoaderRoute: typeof KinshasaHotelsRouteImport
      parentRoute: typeof KinshasaRoute
    }
    '/kinshasa/affaires': {
      id: '/kinshasa/affaires'
      path: '/affaires'
      fullPath: '/kinshasa/affaires'
      preLoaderRoute: typeof KinshasaAffairesRouteImport
      parentRoute: typeof KinshasaRoute
    }
    '/aeroport/services': {
      id: '/aeroport/services'
      path: '/services'
      fullPath: '/aeroport/services'
      preLoaderRoute: typeof AeroportServicesRouteImport
      parentRoute: typeof AeroportRoute
    }
    '/aeroport/boutiques': {
      id: '/aeroport/boutiques'
      path: '/boutiques'
      fullPath: '/aeroport/boutiques'
      preLoaderRoute: typeof AeroportBoutiquesRouteImport
      parentRoute: typeof AeroportRoute
    }
  }
}

interface AeroportRouteChildren {
  AeroportBoutiquesRoute: typeof AeroportBoutiquesRoute
  AeroportServicesRoute: typeof AeroportServicesRoute
}

const AeroportRouteChildren: AeroportRouteChildren = {
  AeroportBoutiquesRoute: AeroportBoutiquesRoute,
  AeroportServicesRoute: AeroportServicesRoute,
}

const AeroportRouteWithChildren = AeroportRoute._addFileChildren(
  AeroportRouteChildren,
)

interface KinshasaRouteChildren {
  KinshasaAffairesRoute: typeof KinshasaAffairesRoute
  KinshasaHotelsRoute: typeof KinshasaHotelsRoute
  KinshasaVisiterRoute: typeof KinshasaVisiterRoute
}

const KinshasaRouteChildren: KinshasaRouteChildren = {
  KinshasaAffairesRoute: KinshasaAffairesRoute,
  KinshasaHotelsRoute: KinshasaHotelsRoute,
  KinshasaVisiterRoute: KinshasaVisiterRoute,
}

const KinshasaRouteWithChildren = KinshasaRoute._addFileChildren(
  KinshasaRouteChildren,
)

interface PreparerRouteChildren {
  PreparerEnregistrementRoute: typeof PreparerEnregistrementRoute
  PreparerFamillesRoute: typeof PreparerFamillesRoute
  PreparerSecuriteRoute: typeof PreparerSecuriteRoute
}

const PreparerRouteChildren: PreparerRouteChildren = {
  PreparerEnregistrementRoute: PreparerEnregistrementRoute,
  PreparerFamillesRoute: PreparerFamillesRoute,
  PreparerSecuriteRoute: PreparerSecuriteRoute,
}

const PreparerRouteWithChildren = PreparerRoute._addFileChildren(
  PreparerRouteChildren,
)

interface TransportsRouteChildren {
  TransportsBusRoute: typeof TransportsBusRoute
  TransportsTaxiRoute: typeof TransportsTaxiRoute
}

const TransportsRouteChildren: TransportsRouteChildren = {
  TransportsBusRoute: TransportsBusRoute,
  TransportsTaxiRoute: TransportsTaxiRoute,
}

const TransportsRouteWithChildren = TransportsRoute._addFileChildren(
  TransportsRouteChildren,
)

interface VolsRouteChildren {
  VolsArriveesRoute: typeof VolsArriveesRoute
  VolsCompagniesRoute: typeof VolsCompagniesRoute
  VolsDepartsRoute: typeof VolsDepartsRoute
  VolsDetailRoute: typeof VolsDetailRoute
}

const VolsRouteChildren: VolsRouteChildren = {
  VolsArriveesRoute: VolsArriveesRoute,
  VolsCompagniesRoute: VolsCompagniesRoute,
  VolsDepartsRoute: VolsDepartsRoute,
  VolsDetailRoute: VolsDetailRoute,
}

const VolsRouteWithChildren = VolsRoute._addFileChildren(VolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  AeroportRoute: AeroportRouteWithChildren,
  ContactRoute: ContactRoute,
  DestinationsRoute: DestinationsRoute,
  KinshasaRoute: KinshasaRouteWithChildren,
  ParkingRoute: ParkingRoute,
  PreparerRoute: PreparerRouteWithChildren,
  PresseRoute: PresseRoute,
  RecrutementRoute: RecrutementRoute,
  RegieRoute: RegieRoute,
  TransportsRoute: TransportsRouteWithChildren,
  VolsRoute: VolsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
